version: '3'
services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    volumes:
    - "./utml-0.0.1-SNAPSHOT.jar:/utml-0.0.1-SNAPSHOT.jar"
    container_name: utml_dev
    expose:
      - 8080
    ports:
        - 8080:8080
    env_file:
      - .env.dev.docker
    depends_on:
      - db
  ngnix:
    image: nginx
    ports:
      - 80:80
      - 443:443
    links:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  db:
    image: "postgres"
    container_name: db
    ports:
      - 5432:5432
    env_file:
      - .env.dev.docker


